apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # Base64 encoded value of 's3cureP@ssw0rd_2025!'
  # To generate: echo -n 's3cureP@ssw0rd_2025!' | base64
  redis-password: czNjdXJlUEBzc3cwcmRfMjAyNSE=