apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Redis configuration
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    ## Persistence
    # save 900 1
    # save 300 10
    # save 60 10000
    
    # Security
    protected-mode no
    # Password will be set via environment variable

    # Logging
    loglevel notice

    # Performance
    databases 16