/**
 * Aiagentschemamigrations.ts.ts
 *
 * Entity class generated from PostgreSQL table: Entity class generated from PostgreSQL table: public.ai_agent_schema_migrations.AiAgentSchemaMigrations.ts
 *
 * Auto-generated on 2025-10-11
 * Do not edit this file manually.
 */

import { AbstractRepository, Entity } from "../repository/abstractRepository";
import { Column } from "../repository/annotations/Column";
import { Find } from "../repository/annotations/find";
import { Id } from "../repository/annotations/Id";
import { repository } from "../repository/repository";
export class AiAgentSchemaMigrations extends Entity<string> {

   private version: string;
   private appliedAt?: Date;
   private description?: string;

   constructor({ version, appliedAt, description }: { version: string, appliedAt?: Date, description?: string }) {
      super();
      this.version = version;
      this.appliedAt = appliedAt;
      this.description = description;
   }

   @Id('version')
   public getId(): string {
      return this.version;
   }

   public getVersion(): string {
      return this.version;
   }

   @Column({ columnName: 'applied_at', notNull: true, hasDefault: true })
   public getAppliedAt(): Date | undefined {
      return this.appliedAt;
   }

   @Column({ columnName: 'description' })
   public getDescription(): string | undefined {
      return this.description;
   }

   public setAppliedAt(appliedAt?: Date) {
      this.appliedAt = appliedAt;
   }

   public setDescription(description?: string) {
      this.description = description;
   }

}

class AiAgentSchemaMigrationsRepository extends AbstractRepository<AiAgentSchemaMigrations> {

   constructor() {
      super('ai_agent_schema_migrations', AiAgentSchemaMigrations);
   }

   /**
    * Find migration by version (string-based ID)
    */
   @Find()
   public async findByVersion(version: string): Promise<AiAgentSchemaMigrations | null> {
      // Implementation provided by @Find decorator
      return null;
   }

   /**
    * Get all applied migrations ordered by version
    */
   @Find()
   public async findAllOrderByVersionAsc(): Promise<AiAgentSchemaMigrations[]> {
      // Implementation provided by @Find decorator
      return [];
   }

}

const aiagentschemamigrationsRepository = new AiAgentSchemaMigrationsRepository();

repository.set(AiAgentSchemaMigrations, aiagentschemamigrationsRepository);

export default aiagentschemamigrationsRepository;
