/**
 * Aiagentuser.ts.ts
 *
 * Entity class generated from PostgreSQL table: Entity class generated from PostgreSQL table: public.ai_agent_user.AiAgentUser.ts
 *
 * Auto-generated on 2025-10-12
 * Do not edit this file manually.
 */

import { AbstractRepository, Entity } from "../repository/abstractRepository";
import { Column } from "../repository/annotations/Column";
import { Find } from "../repository/annotations/find";
import { Id } from "../repository/annotations/Id";
import { OneToMany } from "../repository/annotations/OneToMany";
import { repository } from "../repository/repository";
import { AiAgentSession } from './ai-agent-session';
export class AiAgentUser extends Entity<number> {

   private id?: number;
   private login: string;
   private password: string;
   private hashVersion: string;
   private isAdmin: boolean;
   private createdAt?: Date;
   private updatedAt?: Date;
   private sessions?: AiAgentSession[];

   constructor({ id, login, password, hashVersion, isAdmin, createdAt, updatedAt, sessions }: { id?: number, login: string, password: string, hashVersion?: string, isAdmin?: boolean, createdAt?: Date, updatedAt?: Date, sessions?: AiAgentSession[] }) {
      super();
      this.id = id;
      this.login = login;
      this.password = password;
      this.hashVersion = hashVersion ?? 'hmac';
      this.isAdmin = isAdmin ?? false;
      this.createdAt = createdAt;
      this.updatedAt = updatedAt;
      this.sessions = sessions;
   }

   @Id('id')
   public getId(): number | undefined {
      return this.id;
   }

   @Column({ columnName: 'login', notNull: true, unique: true })
   public getLogin(): string {
      return this.login;
   }

   @Column({ columnName: 'password', notNull: true })
   public getPassword(): string {
      return this.password;
   }

   @Column({ columnName: 'hash_version', notNull: true, hasDefault: true })
   public getHashVersion(): string {
      return this.hashVersion;
   }

   @Column({ columnName: 'is_admin', notNull: true, hasDefault: true })
   public getIsAdmin(): boolean {
      return this.isAdmin;
   }

   @Column({ columnName: 'created_at', notNull: true, hasDefault: true })
   public getCreatedAt(): Date | undefined {
      return this.createdAt;
   }

   @Column({ columnName: 'updated_at', notNull: true, hasDefault: true })
   public getUpdatedAt(): Date | undefined {
      return this.updatedAt;
   }

   @OneToMany({ target: () => AiAgentSession, mappedBy: 'user_login' })
   public getSessions(): AiAgentSession[] | undefined {
      return this.sessions;
   }

   public setPassword(password: string): void {
      this.password = password;
   }

   public setHashVersion(hashVersion: string): void {
      this.hashVersion = hashVersion;
   }

   public setIsAdmin(isAdmin: boolean): void {
      this.isAdmin = isAdmin;
   }

   public setCreatedAt(createdAt?: Date) {
      this.createdAt = createdAt;
   }

   public setUpdatedAt(updatedAt?: Date) {
      this.updatedAt = updatedAt;
   }

}

class AiAgentUserRepository extends AbstractRepository<AiAgentUser> {

   constructor() {
      super('ai_agent_user', AiAgentUser);
   }

   // Auto-generated finder methods for unique columns
   @Find()
   public async findByLogin(login: string): Promise<AiAgentUser | null> {
      return null;
   }

}

const aiagentuserRepository = new AiAgentUserRepository();

repository.set(AiAgentUser, aiagentuserRepository);

export default aiagentuserRepository;
