/**
 * Aiagentdocumenttype.ts.ts
 *
 * Entity class generated from PostgreSQL table: Entity class generated from PostgreSQL table: public.ai_agent_document_type.AiAgentDocumentType.ts
 *
 * Auto-generated on 2025-10-12
 * Do not edit this file manually.
 */

import { AbstractRepository, Entity } from "../repository/abstractRepository";
import { Column } from "../repository/annotations/Column";
import { Find } from "../repository/annotations/find";
import { Id } from "../repository/annotations/Id";
import { OneToMany } from "../repository/annotations/OneToMany";
import { repository } from "../repository/repository";
import { AiAgentDocument } from './ai-agent-document';
export class AiAgentDocumentType extends Entity<number> {

   private id?: number;
   private type: string;
   private createdAt?: Date;
   private documents?: AiAgentDocument[];

   constructor({ id, type, createdAt, documents }: { id?: number, type: string, createdAt?: Date, documents?: AiAgentDocument[] }) {
      super();
      this.id = id;
      this.type = type;
      this.createdAt = createdAt;
      this.documents = documents;
   }

   @Id('id')
   public getId(): number | undefined {
      return this.id;
   }

   @Column({ columnName: 'type', notNull: true, unique: true })
   public getType(): string {
      return this.type;
   }

   @Column({ columnName: 'created_at', notNull: true, hasDefault: true })
   public getCreatedAt(): Date | undefined {
      return this.createdAt;
   }

   @OneToMany({ target: () => AiAgentDocument, mappedBy: 'type_id' })
   public getDocuments(): AiAgentDocument[] | undefined {
      return this.documents;
   }

   public setCreatedAt(createdAt?: Date) {
      this.createdAt = createdAt;
   }

}

class AiAgentDocumentTypeRepository extends AbstractRepository<AiAgentDocumentType> {

   constructor() {
      super('ai_agent_document_type', AiAgentDocumentType);
   }

   // Auto-generated finder methods for unique columns
   @Find()
   public async findByType(type: string): Promise<AiAgentDocumentType | null> {
      return null;
   }

}

const aiagentdocumenttypeRepository = new AiAgentDocumentTypeRepository();

repository.set(AiAgentDocumentType, aiagentdocumenttypeRepository);

export default aiagentdocumenttypeRepository;
