/**
 * Aiagentsession.ts.ts
 *
 * Entity class generated from PostgreSQL table: Entity class generated from PostgreSQL table: public.ai_agent_session.AiAgentSession.ts
 *
 * Auto-generated on 2025-10-04
 * Do not edit this file manually.
 */

import { AbstractRepository, Entity } from "../abstractRepository";
import { Column } from "../annotations/Column";
import { Find } from "../annotations/find";
import { Id } from "../annotations/Id";
import { repository } from "../repository";
export class AiAgentSession extends Entity {

   private id?: number;
   private name: string;
   private userLogin: string;
   private createdAt?: Date;
   private ping?: Date;

   constructor({ id, name, userLogin, createdAt, ping }: { id?: number, name: string, userLogin: string, createdAt?: Date, ping?: Date }) {
      super();
      this.id = id;
      this.name = name;
      this.userLogin = userLogin;
      this.createdAt = createdAt;
      this.ping = ping;
   }

   @Id('id')
   public getId(): number | undefined {
      return this.id;
   }

   @Column({ columnName: 'name', notNull: true, unique: true })
   public getName(): string {
      return this.name;
   }

   @Column({ columnName: 'user_login', notNull: true })
   public getUserLogin(): string {
      return this.userLogin;
   }

   @Column({ columnName: 'created_at' })
   public getCreatedAt(): Date | undefined {
      return this.createdAt;
   }

   @Column({ columnName: 'ping' })
   public getPing(): Date | undefined {
      return this.ping;
   }

   public setPing(ping?: Date) {
      this.ping = ping;
   }

}

export class AiAgentSessionRepository extends AbstractRepository<AiAgentSession> {

   constructor() {
      super('ai_agent_session', AiAgentSession);
   }

   @Find()
   public async findByUserLogin(userLogin: string): Promise<AiAgentSession | null> {
      return null;
   }
}

const sessionRepository = new AiAgentSessionRepository();

repository.set(AiAgentSession, sessionRepository);

export default sessionRepository;
