apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiagent
  labels:
    app: aiagent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aiagent
  template:
    metadata:
      labels:
        app: aiagent
    spec:
      containers:
        - name: aiagent
          image: {{ .Values.aiagent.image.repository }}:{{ .Values.aiagent.image.tag }}
          ports:
            - containerPort: {{ .Values.aiagent.targetPort }}
          env:
            - name: DB_HOST
              value: "postgres-service"
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"