apiVersion: v1
kind: Service
metadata:
  name: aiagent-service
spec:
  type: ClusterIP
  selector:
    app: aiagent
  ports:
    - protocol: TCP
      port: {{ .Values.aiagent.port }}
      targetPort: {{ .Values.aiagent.targetPort }}